export const DELETE_ALL_SUCCESS = 'DELETE_ALL_SUCCESS';
export const LOAD_UNPLANNEDMONEY_SUCCESS = 'LOAD_UNPLANNEDMONEY_SUCCESS';
export const UPDATE_UNPLANNEDMONEY_SUCCESS = 'UPDATE_UNPLANNEDMONEY_SUCCESS';
