export const DELETE_UNPLANNEDMONEY_SUCCESS = 'DELETE_UNPLANNEDMONEY_SUCCESS';
export const LOAD_UNPLANNEDMONEY_SUCCESS = 'LOAD_UNPLANNEDMONEY_SUCCESS';
export const UPDATE_UNPLANNEDMONEY_SUCCESS = 'UPDATE_UNPLANNEDMONEY_SUCCESS';
