export const CREATE_MONEY_ERROR = 'CREATE_MONEY_ERROR';
export const CREATE_MONEY_SUCCESS = 'CREATE_MONEY_SUCCESS';

export const LOAD_MONEYS_SUCCESS = 'LOAD_MONEYS_SUCCESS';
export const UNLOAD_MONEYS_SUCCESS = 'UNLOAD_MONEYS_SUCCESS';
