export const CREATE_EXPENSE_ERROR = 'CREATE_EXPENSE_ERROR';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';

export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS';
export const UNLOAD_EXPENSES_SUCCESS = 'UNLOAD_EXPENSES_SUCCESS';
